URL = "https://www.saucedemo.com/"
USERNAME_ID = "user-name"
PASSWORD_ID = "password"
LOGIN_BTN_ID = "login-button"
LOGOUT_BTN_ID = "logout_sidebar_link"
PASSWORD = "secret_sauce"
STANDARD_USER = "standard_user"
LOCKED_OUT_USER = "locked_out_user"
PROBLEM_USER = "problem_user"
PERFORMANCE_GLITCH_USER = "performance_glitch_user"

ERROR_MESSAGE_XPATH = "/html/body/div/div/div[2]/div[1]/div/div/form/div[3]/h3"
CHECKOUT_ERROR_MESSAGE_XPATH = "/html/body/div/div/div/div[2]/div/form/div[1]/div[4]/h3"
ERROR_ICON_CLASS = "error_icon"
INVENTORY_ITEM_CLASS = "inventory_item"
INVENTORY_BUTTON_CLASS = "btn_inventory"
SHOPPING_CART_BADGE_CLASS = "shopping_cart_badge"
SHOPPING_CART_CLASS = "shopping_cart_link"
CHECK_OUT_FIRSTNAME_ID = "first-name"
CHECK_OUT_LASTNAME_ID = "last-name"
CHECK_OUT_POSTALCODE_ID = "postal-code"
CHECKOUT_BTN_ID = "checkout"
CONTINUE_BTN_ID = "continue"
FIRST_ITEM_XPATH = "/html/body/div/div/div/div[2]/div/div/div/div[1]/div[2]/div[1]/a/div"
FIRST_ITEM_PRICE_XPATH = "/html/body/div/div/div/div[2]/div/div/div/div[1]/div[2]/div[2]/div"
CART_ITEM_CLASS = "cart_item"
MENU_BTN_ID = "react-burger-menu-btn"
RESET_APP_STATE_BTN_ID = "reset_sidebar_link"

# Error Messages
INVALID_LOGIN_MESSAGE = "Epic sadface: Username and password do not match any user in this service"
LOCKED_OUT_USER_MESSAGE = "Epic sadface: Sorry, this user has been locked out."
BLANK_PASSWORD_MESSAGE = "Epic sadface: Password is required"
BLANK_USERNAME_MESSAGE = "Epic sadface: Username is required"
FIRST_NAME_MESSAGE = "Error: First Name is required"
LASTNAME_MESSAGE = "Error: Last Name is required"
POSTAL_CODE_MESSAGE = "Error: Postal Code is required"